# Generated by Django 2.2 on 2022-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_messageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageitem',
            name='recipient',
            field=models.CharField(max_length=255),
        ),
    ]
