# Generated by Django 2.2 on 2022-05-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_auto_20220525_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_staff',
        ),
    ]
